version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-deploy"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-solc"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-vyper"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-chai-matchers"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-verify"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-toolbox"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
