version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk
      # zksync-web3 package relies on older versions of ethers package
      - dependency-name: ethers

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-deploy"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk
      # zksync-web3 package relies on older versions of ethers package
      - dependency-name: ethers

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync-upgradable"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk
      # zksync-web3 package relies on older versions of ethers package
      - dependency-name: ethers

  - package-ecosystem: "npm"
    directory: "/packages/hardhat-zksync"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
    ignore:
      # Chalk 5 is ESM. To use Chalk with TypeScript or a build tool, it is recommended to stay on Chalk 4 for now. [Read more.](https://github.com/chalk/chalk/releases/tag/v5.0.0)
      - dependency-name: chalk
      # zksync-web3 package relies on older versions of ethers package
      - dependency-name: ethers
